### ISSUE TITLE
[BUG] unwanted **size-plugin.json** file

### ISSUE THREAD

**Issue by jimblue** [GoogleChromeLabs/size-plugin#28]
Hello,

Since latest release 2.0.0 a **size-plugin.json** file is created.
Passing option `writeFile: false` doesn't help to prevent that.

I guess this is bug introduced with the new release as I nothing change on my side.

Cheers :)

**Comment by jimblue** [comment]
Just a friendly ping... have you been able to reproduce the bug on your side?

**Comment by kuldeepkeshwar** [comment]
@jimblue yup, it was my mistake.
fixed in #27

**Comment by jimblue** [comment]
Hope this can be merge soon :) thank you

**Comment by developit** [comment]
@jimblue for now I've published a patch update (2.0.1) that fixes `writeFile:false` so it doesn't write the file.

**Comment by jimblue** [comment]
awesome tks @developit

**Comment by sectsect** [comment]
This problem have resolved?
The option `writeFile: false` still create a `size-plugin.json` file on v2.0.1.

**Comment by jimblue** [comment]
Indeed @sectsect is right, just try with version `2.0.1`... not resolved!

**Comment by jimblue** [comment]
@developit can you reopen this issue please

**Comment by jimblue** [comment]
@developit ?

**Comment by sectsect** [comment]
@developit 
Can you reopen this issue?
